AWSTemplateFormatVersion: '2010-09-09'
Description: Simple template to output BucketName and ObjectKey values for testing.

Parameters:
  BucketName:
    Type: String
    Description: Name of the S3 bucket where the Lambda artifacts are stored.

  ObjectKey:
    Type: String
    Description: S3 Key of the Lambda artifact (ZIP file path in S3).

Resources:
  # Placeholder Lambda function for testing bucket and key access
  TestLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: TestFunction
      Handler: index.handler
      Runtime: python3.12
      Code:
        S3Bucket: !Ref BucketName
        S3Key: !Ref ObjectKey
      Role: !GetAtt LambdaExecutionRole.Arn

  # Execution Role for Lambda Function (minimal permissions for testing)
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: LambdaExecutionTestRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: BasicLambdaPermissions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "arn:aws:logs:*:*:*"

Outputs:
  BucketNameOutput:
    Description: The Bucket Name being tested
    Value: !Ref BucketName

  ObjectKeyOutput:
    Description: The Object Key (ZIP file path) being tested
    Value: !Ref ObjectKey
