AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for creating DynamoDB, API Gateway, Lambda functions with a shared layer for item management.

Parameters:
  DynamoDBTableName:
    Type: String
    Description: Name of the DynamoDB table to store items.
    Default: ShoppingItem

  ArtifactS3Bucket:
    Type: String
    Default: "codepipeline-us-east-1-534781109788"
    
  BucketName:
    Type: String
    Description: Name of the S3 bucket where the Lambda artifacts are stored.

  AddItemObjectKey:
    Type: String
    Description: S3 Key of the AddItem Lambda artifact.

  RemoveItemObjectKey:
    Type: String
    Description: S3 Key of the RemoveItem Lambda artifact.

  LayerObjectKey:
    Type: String
    Description: S3 Key of the Lambda layer artifact.

Resources:
  # DynamoDB Table
  MyDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref DynamoDBTableName
      AttributeDefinitions:
        - AttributeName: itemId
          AttributeType: S
      KeySchema:
        - AttributeName: itemId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  # Lambda Layer
  LambdaLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: CommonLambdaLayer
      Description: Layer for shared dependencies
      CompatibleRuntimes:
        - python3.12
      Content:
        S3Bucket: !Ref BucketName
        S3Key: !Ref LayerObjectKey

  # AddItem Lambda Function
  AddItemLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: AddItemFunction
      Handler: lambda_function.add_item_handler
      Runtime: python3.12
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref BucketName
        S3Key: !Ref AddItemObjectKey
      Layers:
        - !Ref LambdaLayer
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref DynamoDBTableName

  # RemoveItem Lambda Function
  RemoveItemLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: RemoveItemFunction
      Handler: lambda_function.remove_item_handler
      Runtime: python3.12
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref BucketName  
        S3Key: !Ref RemoveItemObjectKey
      Layers:
        - !Ref LambdaLayer
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref DynamoDBTableName

  # Execution Role for Lambda Functions
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: LambdaExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: DynamoDBAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:DeleteItem
                Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${DynamoDBTableName}"
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "arn:aws:logs:*:*:*"

  # IAM Policy for CloudFormationExecutionRole to manage API Gateway resources
  ApiGatewayPolicyForCloudFormationExecutionRole:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: ApiGatewayPolicy
      Roles:
        - !Ref CloudFormationExecutionRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - apigateway:POST
              - apigateway:PATCH
              - apigateway:DELETE
              - apigateway:GET
              - apigateway:PUT
            Resource: "arn:aws:apigateway:*::/restapis/*"


  # API Gateway for AddItem and RemoveItem
  MyRestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: MyApiGateway

  AddItemResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt MyRestApi.RootResourceId
      PathPart: additem
      RestApiId: !Ref MyRestApi

  RemoveItemResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt MyRestApi.RootResourceId
      PathPart: removeitem
      RestApiId: !Ref MyRestApi

      
  AddItemMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: POST
      ResourceId: !Ref AddItemResource
      RestApiId: !Ref MyRestApi
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub
          - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AddItemLambdaFunctionArn}/invocations
          - { AddItemLambdaFunctionArn: !GetAtt AddItemLambdaFunction.Arn }
  
  RemoveItemMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: DELETE
      ResourceId: !Ref RemoveItemResource
      RestApiId: !Ref MyRestApi
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: DELETE
        Uri: !Sub
          - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${RemoveItemLambdaFunctionArn}/invocations
          - { RemoveItemLambdaFunctionArn: !GetAtt RemoveItemLambdaFunction.Arn }
    
      

  # API Gateway Permissions for Lambda Functions
  AddItemLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref AddItemLambdaFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${MyRestApi}/*"

  RemoveItemLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref RemoveItemLambdaFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${MyRestApi}/*"

Outputs:
  AddItemLambdaFunctionArn:
    Description: ARN of the Add Item Lambda function
    Value: !GetAtt AddItemLambdaFunction.Arn

  RemoveItemLambdaFunctionArn:
    Description: ARN of the Remove Item Lambda function
    Value: !GetAtt RemoveItemLambdaFunction.Arn

  LambdaLayerArn:
    Description: ARN of the shared Lambda Layer
    Value: !Ref LambdaLayer

  DynamoDBTableNameOutput:
    Description: Name of the DynamoDB table
    Value: !Ref MyDynamoDBTable

  RestApiId:
    Description: ID of the API Gateway REST API
    Value: !Ref MyRestApi
 