version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install --upgrade pip
      - pip install pytest moto boto3

  test_code:
    commands:
      - echo "Running tests for addItem"
      - pytest lambda_functions/addItem/test_addItem.py --junitxml=addItem_report.xml  # Chạy test cho addItem
      - echo "Running tests for removeItem"
      - pytest lambda_functions/removeItem/test_removeItem.py --junitxml=removeItem_report.xml  # Chạy test cho removeItem
  build:
    commands:
      - echo "Preparing Lambda function files without zipping"
      - mkdir -p python
      - pip install -r lambda_functions/lambda_layer_requirements.txt -t python
      - echo "Contents of python directory:"
      - ls -R python  # List files in the python directory for verification

artifacts:
  discard-paths: yes  # This will remove the path structure in the output artifacts
  files:
    - lambda_functions/addItem/lambda_function.py  # Include addItem function
    - lambda_functions/removeItem/lambda_function.py  # Include removeItem function
  secondary-artifacts:
    addItemArtifact:
      files:
        - lambda_functions/addItem/lambda_function.py  # Artifact for addItem
      discard-paths: yes  # Discard parent directory paths
    removeItemArtifact:
      files:
        - lambda_functions/removeItem/lambda_function.py  # Artifact for removeItem
      discard-paths: yes  # Discard parent directory paths
    layerArtifact:
      files:
        - 'python/**/*'  # Including all files in the python directory for layer

